#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

cd $(dirname "$0")
source lib/utils.sh

if [[ $GITHUB_TOKEN ]]; then
  echo "-----> Updating deployment status on GitHub ..."

  docker_run deploy_status success
fi
