#!/usr/bin/env bash
[[ $DOKKU_TRACE ]] && set -x

cd $(dirname "$0")
source lib/utils.sh

APP="$1"
set_envs

if [[ $GITHUB_TOKEN ]]; then
  echo "-----> Updating deployment status on GitHub ..."

  docker_run deploy_status success
fi
